# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Harmonic Works"
title_separator          : "-"
name                     : &name "Maurice"
description              : &description "A living notebook on music, ethics, creativity and the human experience."
url                      : https://harmonicworks.org
baseurl                  : ""
repository               : "harmonicworks.github.io"

# Site Author
author:
  # Biographic information
  avatar           : "https://bpe.show4me.com/media/upload/files/9c/03/9c03b546-1866-4512-a514-8fd6f3ae9f86_256.webp"
  name             : "Maurice"
  pronouns         :
  bio              : "Blending music, code, and ethics. One thoughtful experiment at a time."
  location         : "Earth"
  employer         :
  uri              :
  email            :

  # Academic websites
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=C0xB-GMAAAAJ"
  impactstory      :
  orcid            : "https://orcid.org/0009-0007-8216-6408"
  semantic         :
  pubmed           :
  researchgate     :
  scopus           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "HarmonicWorks"
  kaggle           :
  stackoverflow    :

  # Social media
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       : # Add your username if you have one
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          : # Removed - empty channel for now
  zhihu            :
